<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="he" sourcelanguage="en">
  <context>
    <name>QObject</name>
    <message>
      <location filename="../scriptingpython.cpp" line="484"/>
      <source>Invalid use of %1 function. Expected %2 arguments, but got %3.</source>
      <translation>שימוש לא תקין בפונקציה %1. הציפיה הייתה לקבלת משתנה %2, אך נתקבל %3.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="493"/>
      <source>Unknown error from function %1.</source>
      <translation>שגיאה לא ידועה מפונקציה %1.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="534"/>
      <source>Could not calculate string representation of the Python object passed as argument to the function %1.</source>
      <translation>לא ניתן היה לחשב מחרוזות המייצגת את אובייקט פייתון שהועבר כמשתנה לפונקציה %1.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="550"/>
      <source>Could not find execution context for function %1. This is a bug of Python plugin. Please report it.</source>
      <translation>לא ניתן למצוא הקשר הפעלת פונקציה %1. זהו תקל במתקע פייתון. נא לדווח על כך.</translation>
    </message>
    <message>
      <location filename="../scriptingpython.cpp" line="575"/>
      <source>Error from Python function %1: %2</source>
      <translation>שגיאת פונקציית פייתון %1: %2</translation>
    </message>
  </context>
</TS>
